SELECT COUNT(*) FROM usu_individual_t223;
-- OBS: 4431
SELECT COUNT(*) FROM usu_hogar_t223;
-- OBS: 4884

-- CREAR ID
ALTER TABLE eph_2t_2023.usu_individual_t223 ADD COLUMN ID VARCHAR(100);
UPDATE eph_2t_2023.usu_individual_t223 SET ID = CONCAT(CODUSU, NRO_HOGAR, COMPONENTE);
ALTER TABLE eph_2t_2023.usu_individual_t223
CHANGE COLUMN ID ID VARCHAR(100) NOT NULL ,
ADD UNIQUE INDEX ID_UNIQUE (ID ASC) VISIBLE,
ADD PRIMARY KEY (ID);

ALTER TABLE eph_2t_2023.usu_individual_t223 ADD COLUMN ID_hogar VARCHAR(100);
UPDATE eph_2t_2023.usu_individual_t223 SET ID_hogar = CONCAT(CODUSU, NRO_HOGAR);
ALTER TABLE eph_2t_2023.usu_individual_t223
CHANGE COLUMN ID_hogar ID_hogar VARCHAR(100) NOT NULL ,
ADD INDEX ID_hogar_INDEX (ID_hogar ASC) VISIBLE;

ALTER TABLE eph_2t_2023.usu_hogar_t223 ADD COLUMN ID_hogar VARCHAR(100);
SELECT * FROM eph_2t_2023.usu_hogar_t223;
UPDATE eph_2t_2023.usu_hogar_t223 SET ID_hogar = CONCAT(CODUSU, NRO_HOGAR);
ALTER TABLE eph_2t_2023.usu_hogar_t223
CHANGE COLUMN ID_hogar ID_hogar VARCHAR(100) NOT NULL ,
ADD UNIQUE INDEX ID_UNIQUE (ID_hogar ASC) VISIBLE,
ADD PRIMARY KEY (ID_hogar);

-- AGRUPAR REGISTROS POR REGIONES PARA QUE ME DIGA EL TOTAL Y PORCENTAJE DE OBSERVACIONES DE HOGARES EN CADA UNA DE ELLAS
SELECT t.REGION, COUNT(t.REGION) AS cantidad_observaciones, (COUNT(t.REGION) / MAX(total.total_observaciones) * 100) AS porcentaje_total
FROM usu_hogar_t223 t
CROSS JOIN 
    (SELECT COUNT(*) AS total_observaciones FROM usu_hogar_t223) AS total
GROUP BY t.REGION;

-- Seleccionar solo los trabajadores activos, AGRUPAR REGISTROS POR REGIONES Y CATEGORIA OCUPACIONAL PARA QUE ME DIGA EL TOTAL Y PORCENTAJE DE OBSERVACIONES DE HOGARES POR CATEGORIA OCUPACIONAL POR CADA REGION
SELECT t.REGION,  t.CAT_OCUP, COUNT(t.CAT_OCUP) AS cantidad_ocupados_por_categoria, (COUNT(t.CAT_OCUP) / total.total_ocupados_por_region * 100) AS porcentaje_por_categoria
FROM usu_individual_t223 t 
JOIN 
    (SELECT REGION, COUNT(*) AS total_ocupados_por_region FROM usu_individual_t223 WHERE ESTADO=1 GROUP BY REGION) AS total
ON 
    t.REGION = total.REGION
WHERE ESTADO=1  GROUP BY t.REGION, t.CAT_OCUP  ORDER BY t.REGION, t.CAT_OCUP;

